const products = [
  {
    id: 1,
    marca: "marca 1",
    modelo: "modelo 1",
    precio: 5,
    cpu: "intel",
    ram: "16gb",
    sistemaoperativo: "windows",
    resolucionpantalla: "1024*768",
    bateria: "no",
    camaras: "no",
    dimensiones: "105*225",
    peso: "7kg",
    imagen: "/img/logo.jpg",
  },
  {
    id: 2,
    marca: "marca 2",
    modelo: "modelo 2",
    precio: 5,
    cpu: "intel",
    ram: "16gb",
    sistemaoperativo: "windows",
    resolucionpantalla: "1024*768",
    bateria: "no",
    camaras: "no",
    dimensiones: "105*225",
    peso: "7kg",
    imagen: "/img/logo.jpg",
  },
  {
    id: 3,
    marca: "marca 3",
    modelo: "modelo 3",
    precio: 5,
    cpu: "intel",
    ram: "16gb",
    sistemaoperativo: "windows",
    resolucionpantalla: "1024*768",
    bateria: "no",
    camaras: "no",
    dimensiones: "105*225",
    peso: "7kg",
    imagen: "/img/logo.jpg",
  },
  {
    id: 4,
    marca: "marca 4",
    modelo: "modelo 4",
    precio: 5,
    cpu: "intel",
    ram: "16gb",
    sistemaoperativo: "windows",
    resolucionpantalla: "1024*768",
    bateria: "no",
    camaras: "no",
    dimensiones: "105*225",
    peso: "7kg",
    imagen: "/img/logo.jpg",
  },
  {
    id: 5,
    marca: "marca 5",
    modelo: "modelo 5",
    precio: 5,
    cpu: "intel",
    ram: "16gb",
    sistemaoperativo: "windows",
    resolucionpantalla: "1024*768",
    bateria: "no",
    camaras: "no",
    dimensiones: "105*225",
    peso: "7kg",
    imagen: "/img/logo.jpg",
  },
];

export default products;
